import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "./Navbar/Nav";
import About from "./About/About";
import Banner from "./Banner/Banner";
import Services from "./Services/Services";

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] })

export const metadata = {
  title: "Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="px-[3%] lg:px-[10%] lg:w-auto">
          <Nav />
          <Banner />
          <About />
          <Services />
        </div>

        {children}
      </body>
    </html>
  );
}
